### ISSUE TITLE
db:restore command does not actually restore database

### ISSUE THREAD

**Issue by andrewhl** [heybigname/backup-manager#49]
Running the db:restore command, pulling from AWS S3 to pgsql, using gzip compression, I get the following message: 

Successfully restored /production-backup-2014-12-12 13:00:02.gz from s3 to database pgsql.

Checking my database afterwards, I can confirm that the data has not been restored. I am in my local environment, and using getenv('APP_ENV') in config/local/database.php to specify the environment, as well as db password and username. These are all set up correctly, since my application is running without any issue.

Am I misunderstanding the function of the db:restore command? I believed it would overwrite my database with the sql dump. I can also confirm that the sql dump at /production-backup-2014-12-12 13:00:02.gz is correct and valid. The db:backup command works fine.

**Comment by ShawnMcCool** [comment]
Indeed, that's what the restore command is intended to do. Can you give some additional information on this? Are you still having the problem? Is the DB unusually large? If you insert die statements in the code exposing the database connection details, do they seem correct? Are you getting anything in your log?

**Comment by andrewhl** [comment]
Oh, I meant to say I figured out the issue. I forgot to give my files the .sql extension. Pretty red-faced about that.

**Comment by ShawnMcCool** [comment]
Thanks for following up. If anyone else runs into this, your response may help them.
