### ISSUE TITLE
Dropbox upload

### ISSUE THREAD

**Issue by CodeSkills** [heybigname/backup-manager#52]
Hello,

wanted to ask if there is somehow possible enable overwriting or automatic file name generation.
I want it to daily backup and upload to the dropbox but I would need to each day delete the last day backup or I recieve this error

[League\Flysystem\FileExistsException]   
File already exists at path: Backup-mlw  

Thanks!

**Comment by ShawnMcCool** [comment]
Currently, you would need to add a timestamp. We have plans to rework this package to provide more flexibility. But, without doing that I don't feel like making a tweak to overwrite files is a good short-term solution.

**Comment by CodeSkills** [comment]
So could you please hint me how can I do it without any bad tweaks? Thanks!
