### ISSUE TITLE
AwS adapter not found

### ISSUE THREAD

**Issue by mrgodhani** [heybigname/backup-manager#53]
Hi 

I just recently got this error  

Class 'League\Flysystem\Adapter\AwsS3' not found in /var/www/html/production/project/app/vendor/heybigname/backup-manager/src/Filesystems/Awss3Filesystem.php on line 34

**Comment by GrahamCampbell** [comment]
Yeh, this class was renamed to `League\Flysystem\AwsS3v2\AwsS3Adapter`.

**Comment by mrgodhani** [comment]
@GrahamCampbell  so how do we fix it manually editing the package?

**Comment by GrahamCampbell** [comment]
By sending a pull request. :P

**Comment by ShawnMcCool** [comment]
The newest version 0.3.10 resolves this.
