### ISSUE TITLE
Class 'League\Flysystem\Dropbox\DropboxAdapter not found

### ISSUE THREAD

**Issue by hansvn** [heybigname/backup-manager#60]
Hi, I updated to the latest version (0.3.10) and now I get this error:

PHP Fatal error:  Class 'League\Flysystem\Dropbox\DropboxAdapter' not found in /home/forge/default/vendor/heybigname/backup-manager/src/Filesystems/DropboxFilesystem.php on line 30

maybe this has something to do with the changed dependencies?
v0.3.9 => league/flysystem: >=0.3.1
v0.3.10 => league/flysystem: ~1.0

*edit:
I just tested It and it is indead due to the dependencies.
I installed league/flysystem v0.5.12 and heybigname/backup-manager v0.3.9 and the dropbox backup works fine now

**Comment by GrahamCampbell** [comment]
This is not an issue. You forgot to require the dropbox adapter. Please actually read the list of suggested packages composer gives you.

**Comment by hansvn** [comment]
Ok, you're right. Thanks for the reply!
running composer require league/flysystem-dropbox solved it.

I'm just confused by the tagging that was used: the version went from 0.3.9 to 0.3.10 so that should mean a bugfix with backwards compatibility:

*Given a version number MAJOR.MINOR.PATCH, increment the:
    MAJOR version when you make incompatible API changes,
    MINOR version when you add functionality in a backwards-compatible manner, and
    PATCH version when you make backwards-compatible bug fixes.*
from http://semver.org/

But since it's not (fully) backwards compatible (for example throught a simple composer update) I think it should have been better to release a 0.4.0 version.
